const a = {
    BTC: {
        explorer: "https://test-insight.bitpay.com",
        api: "https://test-insight.bitpay.com/api",
        code: 1,
        decimals: 8,
        forks: ["LTC", "DASH","BCH"],
        fee_label: "Sats",
        // "estimateFee": true,
        base: true,
        name: "Bitcoin",
    },
    BCH: {
        explorer: "https://test-bch-insight.bitpay.com/",
        api: "https://test-bch-insight.bitpay.com/api",
        code: 1,
        decimals: 8,
        fee_label: "BCH",
        name: "Bitcoin Cash",
        ofBase: "BTC",
        forks: [],
    },
    LTC: {
        explorer: "https://testnet.litecore.io",
        api: "https://testnet.litecore.io/api",
        code: 1,
        decimals: 8,
        fee_label: "LTC",
        name: "Litecoin",
        ofBase: "BTC",
        forks: [],
    },
    DASH: {
        explorer: "https://testnet-insight.dashevo.org/insight",
        api: "https://testnet-insight.dashevo.org/insight-api-dash",
        code: 5,
        decimals: 8,
        fee_label: "DASH",
        name: "Dash",
        ofBase: "BTC",
        forks: [],
    },
    ETH: {
        explorer: "https://rinkeby.etherscan.io",
        api: "https://api-rinkeby.etherscan.io/api",
        api_tokens: "https://tokenbalancerinkeby.herokuapp.com/api/balance",
        rpc: "https://rinkeby.infura.io/v3/2294f3b338ad4524aa9186012810e412",
        assets: {
            TRST: {
                hash: "0x87099add3bcc0821b5b151307c147215f839a110",
                ticker: "TRST",
                name: "WeTrust",
                decimals: 6,
            },
        },
        code: 1,
        decimals: 18,
        fee_label: "gwei",
        // "estimateFee": true,
        dualFee: true,
        base: true,
        name: "Ethereum",
        forks: [],
    },
    NEO: {
        explorer: "http://35.243.206.176:4000/",
        api: "http://neoscan.mywish.io/api/main_net/v1",
        code: 1,
        assets: require("./assets/neo.json"),
        decimals: 0,
        fee_label: "GAS",
        base: true,
        name: "Neo",
        forks: [],
    },
    /*
    NANO: {
        explorer: "https://www.nanode.co",
        api:  "http://35.227.18.245:7076/",
        code: 1,
        decimals: 10 ** 30,
        fee_label: "",
        noFee: true,
        base: true,
        name: "Nano",
        forks: [],
        rep: "xrb_17krztbeyz1ubtkgqp9h1bewu1tz8sgnpoiii8q7c9n7gyf9jfmuxcydgufi",
    },
    */
    VET: {
        explorer: "https://testnet.veforge.com",
        api: "https://testnet.veforge.com/api",
        rpc: "https://sync-testnet.vechain.org",
        assets: require("./assets/vet.json"),
        code: 1,
        decimals: 18,
        fee_label: "VTHO",
        noFee: true,
        base: true,
        name: "Vechain",
        forks: [],
        energy_ticker: "VTHO",
        chainTag: 39, // 0x27
    },
    XRP: {
        explorer: "https://xrpcharts.ripple.com/#/transactions",
        api: "https://xrpnode.herokuapp.com/api",
        rpc: "https://s.altnet.rippletest.net:51234",
        code: 1,
        decimals: 6,
        fee_label: "XRP",
        base: true,
        name: "Ripple",
        forks: [],
        node: "test",
        noFee: true,
    },/*
    XLM: {
        explorer: "http://horizon-testnet.stellar.org",
        api: "https://horizon-testnet.stellar.org",
        code: 1,
        decimals: 0,
        fee_label: "XLM",
        base: true,
        name: "Stellar",
        forks: [],
        noFee: true,
    },*/
    EOS: {
        explorer: "https://kylin.eosx.io/",
        api: "https://api-kylin.eoslaomao.com/v1",
        rpc: "https://api-kylin.eoslaomao.com",
        code: 1,
        decimals: 0,
        fee_label: "RAM",
        base: true,
        name: "EOS",
        forks: [],
        noFee: true,
    },    
    /*
    "XMR": {10
        "exp10
            10https://www.nanode.co/",
            10https://www.nanode.co/"
        },estimateFee
        "api": {
            "main": "http://35.227.18.245:7076/",
            "test": "http://35.227.18.245:7076/"
        },
        "code": 128,
        "decimals": 10 ** 18,
    },    */
};

export default a;